name: Weekly GBIF to OBIS Check

on:
  schedule:
    - cron: '0 10 * * 1'  # Every Monday at 10:00 UTC
  workflow_dispatch:

jobs:
  run-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install required R packages
        run: Rscript install-packages.R

      - name: Run GBIF to OBIS check
        run: Rscript gbif_to_obis_check.R
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push summary
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gbif_obis_summary.md
          git commit -m "Update GBIF to OBIS summary [skip ci]" || echo "No changes to commit"
          git push
